### ISSUE TITLE
Numpy deprecated deprecate function in numpy 2.0

### ISSUE THREAD

**Issue by pmallas** [pbrod/nvector#21]
the numpy 'deprecate' function was deprecated in numpy 2.0.  nvector uses this funcition in nvector\util.py

**Comment by mhogan-nwra** [comment]
Hello @pmallas,

I have also encountered this issue. I created a [pull request](https://github.com/pbrod/nvector/pull/20) that has gone ignored for almost two months now. I believe this project is abandoned.

I have begun a new project called [envector](https://github.com/mhogan-nwra/envector) with a working NumPy 2 fix that is available on [PyPI](https://pypi.org/project/envector/). There is no rigorous testing yet.

I welcome any help If you wish to contribute to the project.

**Comment by pmallas** [comment]
Hi thereSure, I can help if needed. I have not done much contributing to GitHub projects, I'm willing to put in some time. I really like this library.PaulSent from my iPhoneOn Aug 29, 2024, at 6:40 PM, Matt ***@***.***> wrote:﻿
Hello @pmallas,
I have also encountered this issue. I created a pull request that has gone ignored for almost two months now. I believe this project is abandoned.
I have begun a new project called envector with a working NumPy 2 fix that is available on PyPI. There is no rigorous testing yet.
I welcome any help If you wish to contribute to the project.

**Comment by mhogan-nwra** [comment]
As of today (2024-09-18), I believe the [envector](https://github.com/mhogan-nwra/envector) package is a more mature product compared to three weeks ago. It has an GitHub Actions CI workflow that validates commits and the end-user documentation is improved in many areas including how to [make the switch to envector](https://github.com/mhogan-nwra/envector/blob/a9bb5825610a12ac7220ba23eeb782bc39a2b707/README.rst?plain=1#L94).

**Comment by pbrod** [comment]
Fixed in e6596f541080a126534cecc00912ce790e14d078.
